### ISSUE TITLE
ImportError:libfairseq2n.so.0: undefined symbol

### ISSUE THREAD

**Issue by duguwanglong** [facebookresearch/fairseq2#16]
from fairseq2.data import Collater
  File "/root/miniconda3/envs/xj/lib/python3.10/site-packages/fairseq2/data/__init__.py", line 7, in <module>
    from fairseq2.data.cstring import CString as CString
  File "/root/miniconda3/envs/xj/lib/python3.10/site-packages/fairseq2/data/cstring.py", line 58, in <module>
    from fairseq2n.bindings.data.string import CString as CString
ImportError: /root/miniconda3/envs/xj/lib/python3.10/site-packages/fairseq2n/lib/libfairseq2n.so.0: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKSs

**Comment by debrupf2946** [comment]
The error message you're encountering suggests that there is an issue with undefined symbols when importing the "fairseq2" module. This typically happens when there is a mismatch between the version of the library or module you are trying to use and the version of the dependencies it expects.

Here are some steps you can take to resolve this issue:

1. **Check Environment**: Make sure you are using the correct environment or virtual environment where you have installed "fairseq2." It appears that you are using Conda, so ensure that your Conda environment is activated correctly.

   ```
   conda activate xj
   ```

2. **Update/Reinstall Dependencies**: It's possible that there is a version mismatch or a corrupted installation of the dependencies. You can try updating or reinstalling the dependencies.

   ```
   pip install --upgrade fairseq2
   ```

   If that doesn't work, you might consider creating a new Conda environment and installing the necessary packages from scratch to ensure a clean environment.

3. **Check Compatibility**: Ensure that the version of "fairseq2" you are using is compatible with the version of PyTorch and other dependencies you have installed. Sometimes, certain versions of libraries are only compatible with specific versions of their dependencies.

4. **Check Environment Variables**: Verify that your environment variables, such as LD_LIBRARY_PATH or PYTHONPATH, are correctly set. Incorrect or missing environment variables can sometimes lead to such errors.

5. **Check Compiler and Build**: If you have compiled "fairseq2" from source, make sure that the compilation was successful without any errors or warnings. Also, ensure that you have all the necessary build tools and libraries installed.

6. **Check for System Updates**: Occasionally, system updates can cause compatibility issues. Make sure your system and system libraries are up to date.

7. **Check for Known Issues**: Sometimes, such issues may be specific to certain versions of libraries or specific environments. Check the project's GitHub repository or documentation for any known issues or workarounds related to your setup.

If none of the above solutions work, please provide more context about your environment and how you installed "fairseq2" so that I can offer more specific guidance.

**Comment by cbalioglu** [comment]
@duguwanglong Last week we release v0.1.1 with updated installation instructions in README. Could you please give it another try? Looks like your PyTorch version or variant does not match the version fairseq2 was built against.

**Comment by cbalioglu** [comment]
@duguwanglong closing this issue for the time-being. If you still experience issues after the v0.1.1 release with the new installation instructions, please re-open it again.
