### ISSUE TITLE
Can I add support to other backends?

### ISSUE THREAD

**Issue by hipudding** [facebookresearch/fairseq2#270]
First of all, thanks for this awesome project. But, I'm wondering whether it's welcome to contribute other backends support except CUDA and CPU.

Support more backends, allowing fairseq2 to be used in more scenarios, what do you think?

**Comment by cbalioglu** [comment]
> First of all, thanks for the awesome project.

@hipudding thank you!

> But, I'm wondering whether it's welcome to contribute other backends support except CUDA and CPU.

We certainly consider adding support for more backends, in particular HIP and MLX. The tricky part will be making sure that we have the right test setup. Right now FAIR is pretty much a CUDA/NVIDIA shop and, as far as I am aware of, we do not use/have access to AMD hardware. That is something we should figure out how to resolve since I do not want us to end up with a half-baked, untested/unused implementation.

Having said that, if you would like to contribute some early support for HIP, please feel free to send a PR. In fact there was #202 from @dc-dc-dc that I haven't had the chance to review due to a very busy H2'23.

**Comment by hipudding** [comment]
I got it. Thanks very much.
