### ISSUE TITLE
Why only one previous word is used as input when predict the current word

### ISSUE THREAD

**Issue by KeepSilentNow** [facebookresearch/fairseq2#286]
I have a question and would greatly appreciate your help! In the [UnitY paper](https://arxiv.org/abs/2212.08055), the translation process is conducted in an autoregressive manner, where each prediction of the next word utilizes all previously predicted words. This is illustrated here:
![image](https://github.com/facebookresearch/fairseq2/assets/124227184/f19bc1b6-b818-4449-8962-9eca7fb03114)

However, in the actual implementation, why is only the previous word used as input each time? This is demonstrated here: [code](https://github.com/facebookresearch/fairseq2/blob/cbffdf0551058c32437088cb4dd60b6ade9b7f94/src/fairseq2/generation/beam_search.py#L662)
```
# fairseq2/generation/beam_search.py
 def _step(self) -> bool:
        # Generate the next step output.
        model_output = self._decode(self.seqs[:, self.step_nr - 1 : self.step_nr])  # here 

        self.state_bag.increment_step_nr()

        logits = model_output.logits
```

**Comment by cbalioglu** [comment]
Hey @KeepSilentNow, the state (to be specific the key/value attention values of previous steps) is preserved in `state_bag` (see the next statement after `self._decode()` in your code snippet). We call this incremental decoding and it is performed as a performance optimization that significantly speeds up inference. Technically the next input still utilizes all previously predicted outputs, but instead of repeatedly performing the same operations on identical past inputs, we cache their intermediate states and reuse them at each step.

**Comment by cbalioglu** [comment]
Closing for now. Feel free to reopen if you have further questions.

**Comment by KeepSilentNow** [comment]
Understood. Thank you very much.
